In [3]:
import numpy as np

In [1]:
l = [1, 2, 3, 4, 5]
l

[1, 2, 3, 4, 5]

In [5]:
n = np.array(l, dtype=int)
n, n.dtype

(array([1, 2, 3, 4, 5]), dtype('int32'))

In [6]:
a = np.square(n)
a

array([ 1,  4,  9, 16, 25])

In [8]:
a = np.array((1,2,3,4,5,6,7,8,9,10))
type(a), a

(numpy.ndarray, array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [9]:
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (10,), 1, 10)

In [10]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
a = np.array([1,2,3])
b = np.array([10,20,30])
c = 2*a + b
c

array([12, 24, 36])

In [13]:
c = np.array([[1,2,3], [4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [14]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

In [17]:
t = np.arange(24).reshape(4, 6)
t, t.ndim

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 2)