### 1. Numpy N-Dimensional Array

In [2]:
import numpy as np

- ndarray(n-dimension array)와 list의 차이

In [3]:
l = [1, 2, 3, 4, 5]
l

[1, 2, 3, 4, 5]

In [4]:
n = np.array([1, 2, 3, 4, 5], dtype=int)
n

array([1, 2, 3, 4, 5])

In [5]:
a = np.square(n)
a

array([ 1,  4,  9, 16, 25])

- 1차원 배열(Vector)

In [6]:
a = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
type(a)

numpy.ndarray

In [7]:
a.dtype, a.shape, a.ndim, a.size

(dtype('int32'), (10,), 1, 10)

In [8]:
# 벡터화 연산
a * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = 2*a + b
c

array([12, 24, 36])

In [10]:
a == 2, b > 10

(array([False,  True, False]), array([False,  True,  True]))

- 2차원 배열(Matrix)

In [11]:
c = np.array([[1,2,3], [4,5,6]])      # == np.arange(1, 7).reshape(2, 3)
print(c)

[[1 2 3]
 [4 5 6]]


In [12]:
c.dtype, c.shape, c.ndim, c.size

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [13]:
t = np.arange(1, 25, 2).reshape(2, 3, 2)
t

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11]],

       [[13, 15],
        [17, 19],
        [21, 23]]])

In [14]:
t.dtype, t.shape, t.ndim, t.size

(dtype('int32'), (2, 3, 2), 3, 12)

- 배열의 인덱싱

In [15]:
a

array([1, 2, 3])

In [16]:
a[0], a[2], a[-1]

(1, 3, 3)

In [17]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
c[0,0], c[-1, 0], c[1, 2]

(1, 4, 6)

- 배열의 슬라이싱

In [19]:
# 리스트 형식에서는 행과 열을 동시에 슬라이싱 불가
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l[:2][1:]

[[4, 5, 6]]

In [20]:
# nparray 형식에서는 행과 열을 동시에 슬라이싱 가능
c = np.arange(1, 10).reshape(3, 3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# 위의 두 행 슬라이싱
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# 오른쪽 두열
c[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [23]:
# 5, 6, 8, 9
c[1:, 1:]

array([[5, 6],
       [8, 9]])

In [24]:
# 1, 4, 3, 6
c[:-1, ::2]

array([[1, 3],
       [4, 6]])

In [25]:
c[::2, ::2]

array([[1, 3],
       [7, 9]])

- 연습문제1

In [26]:
m = np.arange(15).reshape(3, 5)
print(m)
print(m[1,3], m[2,4], m[-1, -1]) 
print(m[1, 1:3], m[1:, 2])
print(m[:2, 3:])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
8 14 14
[6 7] [ 7 12]
[[3 4]
 [8 9]]


- 배열 인덱싱(Fancy indexing)

In [27]:
# idx 값이 True/False이면 True원소와 대치되는 원소 반환
a = np.array([1,2,3,4,5,6,7,8,9,10])
idx = np.array([True, False,True, False,True, False,True, False,True, False])
a[idx]

array([1, 3, 5, 7, 9])

In [28]:
a % 2 == 1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [29]:
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [30]:
# idx 값이 정수값(index)이면, 해당 인덱스의 원소 반환
idx = np.array([1,3,5,7,9])
a[idx]

array([ 2,  4,  6,  8, 10])

- 연습문제2

In [31]:
x = np.arange(1, 21)

print(x[x % 3 == 0])
print(x[x % 4 == 1])
print(x[(x % 3 == 0) &(x % 4 == 1)])        # output : array

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
